spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      sms:
        host: https://dfsns.market.alicloudapi.com
        path: /data/send_sms
        appcode: b87ac9a5933b4a399490cbb34966f0c0


  application:
    name: legmall-third-party

server:
  port: 9000