spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://legmall-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://legmall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party_route
          uri: lb://legmall-third-party
          predicates: # 什么情况下路由给它
            - Path=/api/thirdparty/** # 默认前端项目都带上api前缀，
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://legmall-ware
          predicates: # 什么情况下路由给它
            - Path=/api/ware/** # 默认前端项目都带上api前缀，
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast # 路由给renren-fast，lb代表负载均衡
          predicates: # 什么情况下路由给它
            - Path=/api/** # 默认前端项目都带上api前缀，
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

        - id: legmall_host_route
          uri: lb://legmall-product
          predicates:
            - Host=liengmall.com,item.liengmall.com

        - id: legmall_search_route
          uri: lb://legmall-search
          predicates:
            - Host=search.liengmall.com

        - id: legmall_auth_route
          uri: lb://legmall-auth-server
          predicates:
            - Host=auth.liengmall.com

        - id: legmall_cart_route
          uri: lb://legmall-cart
          predicates:
            - Host=cart.liengmall.com

        - id: legmall_order_route
          uri: lb://legmall-order
          predicates:
            - Host=order.liengmall.com

        - id: legmall_member_route
          uri: lb://legmall-member
          predicates:
            - Host=member.liengmall.com

        - id: legmall_seckill_route
          uri: lb://legmall-seckill
          predicates:
            - Host=seckill.liengmall.com